#!/bin/bash
#SBATCH --time=7-0
#SBATCH --mem=120G
#SBATCH --partition=pibu_el8
#SBATCH --nodes=1
#SBATCH --job-name=Maker
#SBATCH --ntasks-per-node=50

#before launching - pre-processing
#WORKDIR=/data/users/mjacquey/annotation_course/gene_annotation_directory
#mkdir -p $WORKDIR
#cd $WORKDIR
#apptainer exec --bind $WORKDIR \
#    /data/courses/assembly-annotation-course/CDS_annotation/containers/MAKER_3.01.03.sif maker -CTL

COURSEDIR="/data/courses/assembly-annotation-course/CDS_annotation"
WORKDIR="/data/users/mjacquey/annotation_course/gene_annotation_directory"
REPEATMASKER_DIR="/data/courses/assembly-annotation-course/CDS_annotation/softwares/RepeatMasker"
export PATH=$PATH:"/data/courses/assembly-annotation-course/CDS_annotation/softwares/RepeatMasker"

module load OpenMPI/4.1.1-GCC-10.3.0
module load AUGUSTUS/3.4.0-foss-2021a

mpiexec --oversubscribe -n 50 apptainer exec \
    --bind $SCRATCH:/TMP --bind /data --bind $WORKDIR --bind $COURSEDIR --bind $AUGUSTUS_CONFIG_PATH --bind $REPEATMASKER_DIR \
    ${COURSEDIR}/containers/MAKER_3.01.03.sif \
    maker -mpi --ignore_nfs_tmp -TMP /TMP $WORKDIR/maker_opts.ctl $WORKDIR/maker_bopts.ctl $WORKDIR/maker_evm.ctl $WORKDIR/maker_exe.ctl
