#!/bin/bash

#SBATCH --job-name=TEsorter
#SBATCH --partition=pibu_el8
#SBATCH --cpus-per-task=1
#SBATCH --mem=64G
#SBATCH --time=00:40:00

WORKDIR=/data/users/mjacquey/annotation_course/results

#run TEsorter after running the script called 05_extraction

apptainer exec --bind $WORKDIR /data/courses/assembly-annotation-course/CDS_annotation/containers/TEsorter_1.3.0.sif TEsorter \
	$WORKDIR/Copia_sequences.fa -db rexdb-plant
apptainer exec --bind $WORKDIR /data/courses/assembly-annotation-course/CDS_annotation/containers/TEsorter_1.3.0.sif TEsorter \
	$WORKDIR/Gypsy_sequences.fa -db rexdb-plant
