#!/bin/bash
#SBATCH --time=01:00:00
#SBATCH --mem=64G
#SBATCH --partition=pibu_el8
#SBATCH --nodes=1
#SBATCH --job-name=MAKERBIN

COURSEDIR="/data/courses/assembly-annotation-course/CDS_annotation"
MAKERBIN="$COURSEDIR/softwares/Maker_v3.01.03/src/bin"

$MAKERBIN/gff3_merge -s -d /data/users/mjacquey/annotation_course/scripts/ERR11437317.asm.bp.p_ctg.maker.output/ERR11437317.asm.bp.p_ctg_master_datastore_index.log > ERR11437317.asm.bp.p_ctg.all.maker.gff

$MAKERBIN/gff3_merge -n -s -d /data/users/mjacquey/annotation_course/scripts/ERR11437317.asm.bp.p_ctg.maker.output/ERR11437317.asm.bp.p_ctg_master_datastore_index.log > ERR11437317.asm.bp.p_ctg.all.maker.noseq.gff

$MAKERBIN/fasta_merge -d /data/users/mjacquey/annotation_course/scripts/ERR11437317.asm.bp.p_ctg.maker.output/ERR11437317.asm.bp.p_ctg_master_datastore_index.log -o ERR11437317.asm.bp.p_ctg
