#!/bin/bash
#SBATCH --time=01:00:00
#SBATCH --mem=64G
#SBATCH -p pibu_el8
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=50
#SBATCH --job-name=gene_annotation

COURSEDIR="/data/courses/assembly-annotation-course/CDS_annotation"
MAKERBIN="$COURSEDIR/softwares/Maker_v3.01.03/src/bin"

#create a directory
mkdir final

#assign variables
protein="ERR11437317.asm.bp.p_ctg.all.maker.proteins.fasta"
transcript="ERR11437317.asm.bp.p_ctg.all.maker.transcripts.fasta"
gff="ERR11437317.asm.bp.p_ctg.all.maker.noseq.gff"

#variable prefix is random and can be arbitrarily choose (3 or 4 letters maximum)
prefix="ERR"

cp $gff final/${gff}.renamed.gff
cp $protein final/${protein}.renamed.fasta
cp $transcript final/${transcript}.renamed.fasta
cd final

$MAKERBIN/maker_map_ids --prefix $prefix --justify 7 ${gff}.renamed.gff > id.map
$MAKERBIN/map_gff_ids id.map ${gff}.renamed.gff
$MAKERBIN/map_fasta_ids id.map ${protein}.renamed.fasta
$MAKERBIN/map_fasta_ids id.map ${transcript}.renamed.fasta
